INSERT INTO `productos_servicios` (`id_prod_ser`, `id_negocio`, `nombre`, `des`, `duracion`, `restricciones`, `cant-cupos`, `costo`, `tipo`) VALUES 
(101, '10', 'Bicicleta Montañera', 'Bicicleta para viajes a traves de montañas y desensos. Aro 20', NULL, 'mayores de 20 años', '10', '1000', 'p'), 
(102, '10', 'Tienda de Campaña', 'Carpa impermeable de 4x4 par 8 personas, ideal para acampar. Tamaño 6X6 con capacidad para 8 personas', NULL, NULL, '10', '800', 'p'),
(103, '10', 'Sleeping', 'Sleeping de viaje impermeable', NULL, NULL, '20', '400', 'p'),
(104, '10', 'Bolsa ', 'producto indispensable para viajes largos. Capacidad de 200 litros e impermeable, ideal para llevar equipo de supervivencia', NULL, NULL, '10', '700', 'p'),
(105, '10', 'Mochila', 'producto indispensable para viajes largos.', NULL, NULL, '10', '700', 'p'),
(106, '10', 'Bolso Ecologico', 'Bolso Ecologico que ayuda a la no contaminacion del medio ambiente. Viaje cuidando a la fauna y flora!', NULL, NULL, '25', '300', 'p'),
(107, '10', 'Baston', 'producto indispensable para viajes largos.', NULL, NULL, '10', '700', 'p'),
(108, '10', 'Navajas', 'producto indispensable para viajes largos.', NULL, NULL, '10', '700', 'p'),
(109, '10', 'Tomatodos', 'producto indispensable para viajes largos.', NULL, NULL, '10', '700', 'p'),
(110, '10', 'Botas', 'producto indispensable para viajes largos.', NULL, NULL, '10', '700', 'p'),
(111, '10', 'Botellas', 'producto indispensable para viajes largos.', NULL, NULL, '10', '700', 'p'),
(112, '10', 'Kit de Supervivencia', 'producto indispensable para viajes largos.', NULL, NULL, '10', '700', 'p'),
(113, '10', 'Linterna ', 'producto indispensable para viajes largos.', NULL, NULL, '10', '700', 'p'),
(114, '10', 'Encendedor', 'producto indispensable para viajes largos.', NULL, NULL, '10', '700', 'p'),
(115, '10', 'Sogas', 'producto indispensable para viajes largos.', NULL, NULL, '10', '700', 'p'),
(116, '20', 'Hotel Villa Verde', 'Disfrute del hospedaje en uno de los mejores hoteles de Coroico. Buena Vista y comodidad para usted y su familia!', NULL, NULL, '10', '700', 'p'),
(117, '20', 'Hotel Presidente', 'Servicio de Hospedaje 5 estrellas, Buffet matutino, Almuerzo, Cena, area recreacional, llame ya al 70435563', NULL, NULL, '10', '700', 'p'),
(118, '20', 'Viaje Por Bolivia', 'Tour por todos los departamentos de Bolivia, viaje desde La Paz y recorra todos los departamentos', NULL, NULL, '10', '600', 's'),
(119, '20', 'Tour Telefericos', 'Recorrido turistico por todas las lineas de Teleferico de la ciudad maravilla, Sesion de fotos incluido', NULL, NULL, '10', '600', 's'),
(121, '20', 'Tour Mallasa', 'Gran Viaje alredor de Mallasa, disfrute de paisajes extravagantes y buena comida mientras pasea en el BusLaPaz junto a musica en vivo!', NULL, NULL, '10', '600', 's'),
(122, '20', 'Noche de Museos', 'Servicio Turistico ofrece tour alrededor de los museos mas importantes de La Paz, todo museo incluye un guia turistico con experiencia.', NULL, NULL, '10', '600', 's'),
(123, '20', 'Una noche en el Cementerio', 'Tour guiado por los alrededores del Cementerio en horario nocturo, Unica oportunidad, ademas se cuentan con relatores que cuenten las mas populares leyendas', NULL, NULL, '10', '600', 's'),
(124, '20', 'Hospedaje Hotel Gloria', 'lorem fdsa  dsafsfgdh fd g d s ad fa sdgdf  gh fd s gasdgf  sadfsdagret234  546dfs da ds trf t s.', NULL, NULL, '10', '600', 's'),
(125, '20', 'Tour Carnavalero', 'lorem fdsa  dsafsfgdh fd g d s ad fa sdgdf  gh fd s gasdgf  sadfsdagret234  546dfs da ds trf t s.', NULL, NULL, '10', '600', 's'),
(126, '20', 'TOur calle de las Brujas', 'lorem fdsa  dsafsfgdh fd g d s ad fa sdgdf  gh fd s gasdgf  sadfsdagret234  546dfs da ds trf t s.', NULL, NULL, '10', '600', 's'),
(127, '20', 'Visita Museo Cultural', 'lorem fdsa  dsafsfgdh fd g d s ad fa sdgdf  gh fd s gasdgf  sadfsdagret234  546dfs da ds trf t s.', NULL, NULL, '10', '600', 's'),
(128, '20', 'Visita Museo Tiawanaku', 'lorem fdsa  dsafsfgdh fd g d s ad fa sdgdf  gh fd s gasdgf  sadfsdagret234  546dfs da ds trf t s.', NULL, NULL, '10', '800', 's'),
(129, '20', 'Tour Yungas', 'lorem fdsa  dsafsfgdh fd g d s ad fa sdgdf  gh fd s gasdgf  sadfsdagret234  546dfs da ds trf t s.', NULL, NULL, '10', '600', 's'),
(130, '20', 'Carnaval de Oruro', 'lorem fdsa  dsafsfgdh fd g d s ad fa sdgdf  gh fd s gasdgf  sadfsdagret234  546dfs da ds trf t s.', NULL, NULL, '10', '600', 's');


INSERT INTO `publicaciones` (`id_pub`, `id_prod_ser`, `id_usuario`, `fecha`, `titulo`, `des`, `likes`) VALUES 
(NULL, '101', '11', '2022-03-17', 'Promo Bicicleta de Locura', 'Gran Promocion Por el mes del padre, Bicicletas montañeras con 30% de descuentos, Que esperas! No dejes pasar esta oportunidad', '0'), 
(NULL, '102', '11', '2022-03-17', 'Tienda en Oferta', 'Por renovacion de se rematan Tiendas de campaña para Acampar, solo por esta semana! Aproveche y llevese la tienda por solo 800 bs!', '0'), 
(NULL, '116', '12', '2022-03-17', 'Villa Oferta', 'Ven a pasar un fin de semana en el mejor Hotel de Coroico, Grupo Kjarkas en vivo invitadopor el mes del padre! Disfruta en Familia! ', '0'), 
(NULL, '128', '12', '2022-03-17', 'tiawanacu es cultura', 'Disfruta de este Tour a Cargo de el Gobierno Autonomo municipal de la Paz GAMLP y visita las ruinas de una de las mas importantes culturas Andinas', '0'), 
(NULL, '103', '11', '2022-03-17', 'Paquete CArnavalero', 'Grand promocion de Tour carnavalero en La Paz, celebra junto a las mejores comparsas el carnaval paceño y Jiska Anata', '0'), 
(NULL, '104', '12', '2022-03-17', 'Jiska Anata', 'Grand promocion de Tour carnavalero en La Paz, celebra junto a las mejores comparsas el carnaval paceño y Jiska Anata', '0'), 
(NULL, '118', '13', '2022-03-17', 'Traje Tipico CHUTA', 'Grand promocion de Tour carnavalero en La Paz, celebra junto a las mejores comparsas el carnaval paceño y Jiska Anata', '0'), 
(NULL, '119', '13', '2022-03-17', 'Viaje Turistico Coroico', 'Grand promocion de Tour carnavalero en La Paz, celebra junto a las mejores comparsas el carnaval paceño y Jiska Anata', '0'), 
(NULL, '120', '13', '2022-03-17', 'Alasitas Maravilla', 'Grand promocion de Tour carnavalero en La Paz, celebra junto a las mejores comparsas el carnaval paceño y Jiska Anata', '0'); 